### ISSUE TITLE
// TODO

### ISSUE THREAD

**Issue by parthivapsani** [MLH-Fellowship/0.1.1-BLM-Tracker#1]
- [x] Name our project
- [x] Figure out Twitter streaming API
- [x] Implement database and caching system
- [x] Scrub/ filter incoming data
Concurrently:
- [x] Design front end and integrate with streaming - Flask
- [x] Implement Keras classifier for sentiment analysis
- [x] Update heatmap and frontend

**Comment by parthivapsani** [comment]
- [x] Also need to implement threading
* One for Tweepy listener
* One for data scrubbing and filtering
* One for Keras classifier
* One for cache update for front end
* One for timer (?) I don't necessarily know how we'll be able to update the github pages site as it is designed for static sites, maybe we can have flask serve an ajax worker and have the page make new requests to the ajax workers?

**Comment by parthivapsani** [comment]
We should also have a sidebar feature, where when a user clicks on a certain part of the map, we can query tweets from that location to see what people are talking about in different parts of the world

**Comment by parthivapsani** [comment]
And in terms of the timer, I'm thinking we have one Ajax worker to refresh the heatmap and load the cache to the frontend for rendering and another Ajax worker to listen to clicks on the map for sidebar tweet loading. The Ajax worker for the sidebar thing can be a feature we develop near the end of the project if we have time, just wanted to drop that in there
